//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pratica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartament
    {
        public short ID { get; set; }
        public byte HouseID { get; set; }
        public short Number { get; set; }
        public decimal Area { get; set; }
        public byte CountOfRooms { get; set; }
        public byte Section { get; set; }
        public byte Floor { get; set; }
        public bool IsSold { get; set; }
        public int BuildingCost { get; set; }
        public int ApartmentValueAdded { get; set; }
        public byte IsDeleted { get; set; }
    
        public virtual House House { get; set; }
    }
}
