//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pratica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practic0201Ir311Entities : DbContext
    {
        private static Practic0201Ir311Entities _context;
        public Practic0201Ir311Entities()
            : base("name=Practic0201Ir311Entities")
        {
        }
        public static Practic0201Ir311Entities GetContext()
        {
            if (_context == null)
                _context = new Practic0201Ir311Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartament> Apartaments { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<ResidentialComplex> ResidentialComplexes { get; set; }
    }
}
