//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pratica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Practic0201Ir311v2Entities1 : DbContext
    {
        public Practic0201Ir311v2Entities1()
            : base("name=Practic0201Ir311v2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static Practic0201Ir311v2Entities1 _context;
        public static Practic0201Ir311v2Entities1 GetContext()
        {
            if (_context == null)
                _context = new Practic0201Ir311v2Entities1();
            return _context;
        }

        public virtual DbSet<Apartament> Apartaments { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<ResidentialComplex> ResidentialComplexes { get; set; }
        public virtual DbSet<results2> results2 { get; set; }
        public virtual DbSet<rreessuullttss11> rreessuullttss11 { get; set; }
    
        public virtual int CostKV1(Nullable<int> zK)
        {
            var zKParameter = zK.HasValue ?
                new ObjectParameter("ZK", zK) :
                new ObjectParameter("ZK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CostKV1", zKParameter);
        }
    
        public virtual int Prib3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Prib3");
        }
    
        public virtual int PribOtKV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PribOtKV");
        }
    }
}
