//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pratica
{
    using System;
    using System.Collections.Generic;
    
    public partial class results2
    {
        public int Номер { get; set; }
        public string Name { get; set; }
        public Nullable<int> HouseID { get; set; }
        public Nullable<int> Прибыль { get; set; }
    }
}
